### ISSUE TITLE
ctor doesn't work on apple arm64?

### ISSUE THREAD

**Issue by aviramha** [mmastrac/rust-ctor#206]
Hey,
I'm currently trying to use ctor on my local M1 Pro. It seems that ctor doesn't run (even though binary is loaded).
The way I tested it is taking the example and running it with DYLD_INSERT_LIBRARIES. 
I do know that that env var doesn't work with any binary, so I tested it with another binary that I compiled (and saw that the library was loaded).
I also tried testing using gcc and not rust and same behavior so it's not implementation probably - I'm wondering if anyone knows if anything changed - did they remove the feature from the loader?

**Comment by ADKaster** [comment]
The tests for this library fail with both stable `rustc 1.64.0 (a55dd71d5 2022-09-19)` and nightly `rustc 1.66.0-nightly (b8c35ca26 2022-10-15)` rust on macOS Monterey `12.6`. 

```
---- test::test_dylib stdout ----
thread 'test::test_dylib' panicked at 's was unexpected:
+ ctor bin\n++ main start\n+++ ctor STATIC_INT\n+++ ctor lib (-crt-static)\n-- main end\n', tests/src/lib.rs:91:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: tests::test::test_dylib
             at ./src/lib.rs:91:9
   3: tests::test::test_dylib::{{closure}}
             at ./src/lib.rs:66:5
   4: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The "__DATA,__mod_term_func" solution seems to not work anymore. Per this LLVM review, https://reviews.llvm.org/D45578 it sounds like Apple was looking to remove that section in favor of `ataxit`, so this library should probably not special case macOS and iOS anymore.

**Comment by mmastrac** [comment]
Try this with `cargo +nightly --features=used_linker`. This may help.

**Comment by clarkmcc** [comment]
Sadly, this is not working on my M1 Pro on nightly using the used_linker feature flag.

**Comment by mmastrac** [comment]
@clarkmcc I discovered that the used_linker feature flag was actually broken. This is fixed in the latest 0.2.x releases and above.

**Comment by madsmtm** [comment]
This is an issue in `rustc`'s handling of `#[used]`: https://github.com/rust-lang/rust/issues/133491

**Comment by merlinaudio** [comment]
This has recently been merged: https://github.com/rust-lang/rust/pull/133832

**Comment by madsmtm** [comment]
Yeah, this should be fixed since Rust 1.87
